# 包含以下模型
model_name:
  turbidity_predictor: 沉淀池出水浊度预测模型
  dosing_optimizer: 投加药耗优化模型

# 投矾系统时序数据各模型点位表时序数据（历史数据，60个时间步长）
input_point:
  # 沉淀池出水浊度预测模型
  effluent_turbidity:
    FTJZ: 
      WQ_Data_0__Value_fb: FTJZ_Turb_1_Instant #1_反应池浊度
      WQ_Data_3__Value_fb: FTJZ_Turb_2_Instant #2_反应池浊度
      WQ_Data_6__Value_fb: FTJZ_Turb_3_Instant #3_反应池浊度
      WQ_Data_9__Value_fb: FTJZ_Turb_4_Instant #4_反应池浊度
      WQ_Data_1__Value_fb: FTJZ_PH_1_Instant #1_反应池PH
      WQ_Data_4__Value_fb: FTJZ_PH_2_Instant #2_反应池PH
      WQ_Data_7__Value_fb: FTJZ_PH_3_Instant #3_反应池PH
      WQ_Data_10__Value_fb: FTJZ_PH_4_Instant #4_反应池PH
      Flow_water_1_: FTJZ_Flow_jinshui_1_Instant #1#沉淀池进水瞬时流量
      Flow_water_2_: FTJZ_Flow_jinshui_2_Instant
      Flow_water_3_: FTJZ_Flow_jinshui_3_Instant
      Flow_water_4_: FTJZ_Flow_jinshui_4_Instant
      WQ_Data_12__Value_fb: FTJZ_Turb_chushui_1_Instant   # 1_沉淀池出水浊度
      WQ_Data_16__Value_fb: FTJZ_Turb_chushui_2_Instant
      WQ_Data_20__Value_fb: FTJZ_Turb_chushui_3_Instant
      WQ_Data_24__Value_fb: FTJZ_Turb_chushui_4_Instant
      Flow_1__yaohao: FTJZ_yaohao_1_Instant #1_投加流量计—药耗
      Flow_2__yaohao: FTJZ_yaohao_2_Instant #2_投加流量计—药耗
      Flow_3__yaohao: FTJZ_yaohao_3_Instant #3_投加流量计—药耗
      Flow_4__yaohao: FTJZ_yaohao_4_Instant #4_投加流量计—药耗
    YSQC_zz:
      water_temperature_1: FTJZ_temperature_shuimain_Instant #水面水温


  # 投加药耗优化模型，实时数据，当前时刻（从上述历史数据中获取也剋）
  optimized_dose:
    FTJZ: 
      WQ_Data_0__Value_fb: FTJZ_Turb_1_Instant #1_反应池浊度
      WQ_Data_3__Value_fb: FTJZ_Turb_2_Instant #2_反应池浊度
      WQ_Data_6__Value_fb: FTJZ_Turb_3_Instant #3_反应池浊度
      WQ_Data_9__Value_fb: FTJZ_Turb_4_Instant #4_反应池浊度
      WQ_Data_1__Value_fb: FTJZ_PH_1_Instant #1_反应池PH
      WQ_Data_4__Value_fb: FTJZ_PH_2_Instant #2_反应池PH
      WQ_Data_7__Value_fb: FTJZ_PH_3_Instant #3_反应池PH
      WQ_Data_10__Value_fb: FTJZ_PH_4_Instant #4_反应池PH
      Flow_water_1_: FTJZ_Flow_jinshui_1_Instant #1#沉淀池进水瞬时流量
      Flow_water_2_: FTJZ_Flow_jinshui_2_Instant
      Flow_water_3_: FTJZ_Flow_jinshui_3_Instant
      Flow_water_4_: FTJZ_Flow_jinshui_4_Instant
      WQ_Data_12__Value_fb: FTJZ_Turb_chushui_1_Instant   # 1_沉淀池出水浊度
      WQ_Data_16__Value_fb: FTJZ_Turb_chushui_2_Instant
      WQ_Data_20__Value_fb: FTJZ_Turb_chushui_3_Instant
      WQ_Data_24__Value_fb: FTJZ_Turb_chushui_4_Instant
      Flow_1__yaohao: FTJZ_yaohao_1_Instant #1_投加流量计—药耗
      Flow_2__yaohao: FTJZ_yaohao_2_Instant #2_投加流量计—药耗
      Flow_3__yaohao: FTJZ_yaohao_3_Instant #3_投加流量计—药耗
      Flow_4__yaohao: FTJZ_yaohao_4_Instant #4_投加流量计—药耗
    YSQC_zz:
      water_temperature_1: FTJZ_temperature_shuimain_Instant #水面水温
    
